// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyAZdEwwo1BEGHk1p982Pmv4x0pzSAO7g',
    appId: '1:183802544111:web:f1175ed4e39fabd657001a',
    messagingSenderId: '183802544111',
    projectId: 'mobilemodul3',
    authDomain: 'mobilemodul3.firebaseapp.com',
    storageBucket: 'mobilemodul3.appspot.com',
    measurementId: 'G-CK7KS7PW96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRlK6pBFluvQ_AiM_ctbaCuCw3CQRhWwY',
    appId: '1:183802544111:android:3c983d2559fd5b5857001a',
    messagingSenderId: '183802544111',
    projectId: 'mobilemodul3',
    storageBucket: 'mobilemodul3.appspot.com',
  );
}
